name: FastAPI CI Pipeline

# This tells GitHub to run this pipeline every time you push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest # The temporary cloud server GitHub gives you

    steps:
      # 1. Grab your code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Python on the temporary server
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Install your project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx==0.27.2# Adding testing tools

      # 4. Run a quick check to make sure the app can start
      - name: Run tests
        run: |
          pytest
